language: elixir
elixir:
  - 1.5.3
addons:
  postgresql: '9.3'
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
script:
  - mix test
