language: elixir
elixir:
  - 1.5.3
services:
  - postgresql
env:
  global:
    - MIX_ENV=test
    - DB_ENV_POSTGRES_USER=postgres
    - DB_ENV_POSTGRES_PASSWORD=
    - DB_ENV_POSTGRES_HOST=localhost
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix credo list
  - mix test
