web:
  build: .
  ports:
    - "49235:4000"
  links:
    - db:dockerdb
  volumes:
    - .:/app
  command: >
    /bin/bash -c "
      sleep 2;
      mix do ecto.migrate, phoenix.server
    "
db:
  image: kamui/postgresql
  environment:
    - POSTGRESQL_DB=phoenix
    - POSTGRESQL_USER=postgres
    - POSTGRESQL_PASS=postgres
test:
  image: notes_web
  environment:
    - MIX_ENV=test
  volumes_from:
    - web
  links:
    - db:dockerdb
  command: >
    /bin/bash -c "
      sleep 2;
      mix test
    "
