web:
  build: .
  ports:
    - "49235:4000"
  links:
    - db
  volumes:
    - .:/app
  command: >
    /bin/bash -c "
      sleep 2;
      mix do ecto.create, ecto.migrate, phoenix.server
    "
db:
  image: postgres
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_HOST=db

# test:
#   image: notes_web
#   environment:
#     - MIX_ENV=test
#   volumes_from:
#     - web
#   links:
#     - db:dockerdb
#   command: >
#     /bin/bash -c "
#       sleep 2;
#       mix test
#     "
